ENABLE_LOG	true

SERVER	webserv-alpha
{
	HOST			127.0.0.1
	PORT			8080
	PATH			./server_1
	BODY_SIZE		4096
	TIME_OUT		1000 # in milliseconds
	CGI_TIME_OUT	10000

	LOCATION		/
	[
		INDEX			index.html
		PERMISSIONS		get
		TEMP_FILE		uploadedFile
	]
	LOCATION		/cgi-bin
	[
		INDEX			index.html
		PERMISSIONS		get
	]
	LOCATION		/www
	[
		AUTO_INDEX		true
		INDEX			index.html
		PERMISSIONS		get, post, delete
		TEMP_FILE		uploadedFile
	]
	LOCATION		/redirect
	[
		PERMISSIONS		get
		REDIRECT		302 /index.html
	]
	LOCATION		/errorPages
	[
		PERMISSIONS		get
	]

	PAGE_201		errorPages/201.html
	PAGE_400		errorPages/400.html
	PAGE_403		errorPages/403.html
	PAGE_404		errorPages/404.html
	PAGE_413		errorPages/413.html
	PAGE_405		errorPages/405.html
	PAGE_500		errorPages/500.html
	PAGE_501		errorPages/501.html
}

SERVER	webserv-beta
{
	HOST			127.0.0.1
	PORT			9090
	PATH			./server_2
	BODY_SIZE		100000000
	CGI_TIME_OUT	10000

	LOCATION		/
	[
		INDEX			index.html
		PERMISSIONS		get
		TEMP_FILE		uploadedFile
	]
	LOCATION		/cgi-bin
	[
		PERMISSIONS		get
	]
	LOCATION		/www
	[
		AUTO_INDEX		true
		PERMISSIONS		get, post
	]
	LOCATION		/errorPages
	[
		PERMISSIONS		get
	]

	PAGE_201		errorPages/201.html
	PAGE_400		errorPages/400.html
	PAGE_403		errorPages/403.html
	PAGE_404		errorPages/404.html
	PAGE_413		errorPages/413.html
	PAGE_405		errorPages/405.html
	PAGE_500		errorPages/500.html
	PAGE_501		errorPages/501.html
}
